shinyUI(
  fluidPage(
    titlePanel('Props Dash'),
    h5(paste0('Data updated at: ', attr(search_props_raw, 'timestamp'), ' CDT')),
    br(),
    # all the filtering ----
    fluidRow(
      # select a bunch of stuff
      column(width = 2,
             pickerInput('sport', 'Sport',
                         choices = sort(unique(search_props_raw$sport)),
                         selected = sort(unique(search_props_raw$sport)),
                         multiple = TRUE)),
      column(width = 2,
             pickerInput('tipoff_strings', 'Start Times',
                         options = list(`actions-box` = TRUE,
                                        `live-search` = TRUE),
                         choices = sort(unique(search_props_raw$tipoff_string)),
                         selected = sort(unique(search_props_raw$tipoff_string)),
                         multiple = TRUE)),
      column(width = 2,
             pickerInput('player', 'Player',
                         options = list(`actions-box` = TRUE,
                                        `live-search` = TRUE),
                         choices = sort(unique(search_props_raw$tidyplayer)),
                         selected = sort(unique(search_props_raw$tidyplayer)),
                         multiple = TRUE)),
      column(width = 2,
             pickerInput('team', 'Team',
                         options = list(`actions-box` = TRUE,
                                        `live-search` = TRUE),
                         choices = sort(unique(search_props_raw$tidyteam)),
                         selected = sort(unique(search_props_raw$tidyteam)),
                         multiple = TRUE))),
      # #### make sure to fix parentheses for the fluidRow() call above, if uncommenting out the injury_status filters
      # column(width = 2,
      #        pickerInput('injury_status', 'Injury Status',
      #                    options = list(`actions-box` = TRUE,
      #                                   `live-search` = TRUE),
      #                    choices = sort(unique(search_props_raw$injury_status)),
      #                    selected = sort(unique(search_props_raw$injury_status)),
      #                    multiple = TRUE))),
    fluidRow(
      column(width = 2,
             pickerInput('prop', 'Prop',
                         options = list(`actions-box` = TRUE,
                                        `live-search` = TRUE),
                         choices = sort(unique(search_props_raw$prop)),
                         selected = sort(unique(search_props_raw$prop)),
                         # selected = c('first player to score', 'first team to score'),
                         multiple = TRUE)),
      column(width = 2,
             pickerInput('ou', 'Over/Under',
                         options = list(`actions-box` = TRUE,
                                        `live-search` = TRUE),
                         choices = sort(unique(search_props_raw$tidyou)),
                         selected = sort(unique(search_props_raw$tidyou)),
                         multiple = TRUE)),
      column(width = 2,
             numericRangeInput('line', 'Lines',
                         value = c(min(search_props_raw$tidyline, na.rm = TRUE),
                                   max(search_props_raw$tidyline, na.rm = TRUE)))),
                         # value = c(NA, NA))),
      column(width = 2,
             pickerInput('count_books', 'Minimum Books',
                         choices = sort(unique(search_props_raw$count_books)),
                         selected = 1))),
    # all the tabs for filter-dependent outputs ----
    br(),
    tabsetPanel(
      ## search through all props ----
      tabPanel('All Props',
               br(),
               fluidRow(
                 column(width = 12,
                        reactableOutput('search_props')))),
      ## search through props with projections ----
      tabPanel('Projections',
               br(),
               fluidRow(
                 column(width = 12,
                        reactableOutput('projections')))),
      tabPanel('Research',
               br())))
)
